### ISSUE TITLE
Firefox and IE

### ISSUE THREAD

**Issue by smqasim93** [FaiblUG/setIframeHeight#2]
This doesnt work on Firefox and IE as expected. It increases the height of the iframes, but doesnt decrease them. Is there something that needs to be done?

**Comment by jfmaeck** [comment]
Hi @smqasim93, the demo (http://demo.jonasfischer.net/Faibl/setIframeHeight/) is working for me in Firefox and IE.

I just included jQuery 1.9.1 instead of jQuery 2.1.3 and now it is even working in IE8.

Is the demo working on your machine or are you having problems in your on page. If the latter is the case, I can have a look at it if you tell me the url.

**Comment by smqasim93** [comment]
Is there way, I can have any sort of animates when the iframe loads? Like
fadeIn or something?

**Comment by jfmaeck** [comment]
No, sorry.
However, you could try to implement your own loading indicator. Everytime the iframe height changes, a "setIframeHeight" event is triggered on the window object. You could listen for the first event of that type and then hide you animation ...

**Comment by smqasim93** [comment]
Ah! Thanks. Perhaps in a future release you could offer the option of
having animations.

Thanks again.
